### ISSUE TITLE
Filters such as random

### ISSUE THREAD

**Issue by estevancarlos** [ngokevin/aframe-template-component#11]
To my understanding Nunjucks is based off of Jinja and allows for filters. Is that possible in this component? What attempts have been unsuccessful.

**Comment by ngokevin** [comment]
Yeah, I believe it is possible. You will have to talk to the global nunjucks instance to register custom filters.

I made https://github.com/ngokevin/aframe-randomizer-components so I didn't have to. Though it only supports a few components.

**Comment by estevancarlos** [comment]
Okay thanks. I'll look further into that and check out your other component. Thanks.
