### ISSUE TITLE
Add option for JSON data

### ISSUE THREAD

**Issue by msimpson** [ngokevin/aframe-template-component#13]
I wrote a quick component in an attempt to utilize `el.dataset` within the template given an external JSON dataset:

```
  AFRAME.registerComponent('json', {
    schema: {
      src: { default: '' }
    },

    update: function () {
      var el    = this.el;
      var name  = this.data.src.substr(1);
      var asset = document.querySelector(this.data.src);

      asset.addEventListener('loaded', function() {
        el.dataset[name] = asset.data;
      });
    }
  });
```

```
  <a-scene>
    <a-assets>
      <a-asset-item id="manifest" src="assets/manifest.json"></a-asset-item>
      <script id="example" type="text/x-nunjucks-template">
        {% for i in range(0, manifest.length) %}
          <a-entity class="item" look-at="[camera]" data-src="{{ manifest[i].src }}"></a-entity>
        {% endfor %}
      </script>
    </a-assets>

    <a-entity template="src: #example" json="src: #manifest"></a-entity>
```

However, the `loaded` event comes much too late for the actual `el.dataset.manifest` to be used. Therefore, I propose an option to load such data given a `data` attribute on the `template` component itself. At least that way it will trigger an `update` cycle and re-render when the data is actually `loaded`.

Edit:
After implementing this on my own, I see this feature request needs to wait for DOM diffing to be implemented first.

**Blocked by #1**

**Comment by ngokevin** [comment]
Interesting. This gives me an idea. We could use components to define template data.

```js
AFRAME.registerComponent('tree-data', {
  schema: {
    leaves: {default: 500},
    color: {default: 'red'}
  }
});
```

```
<a-entity template="src: #tree; data: tree-data" tree-data="leaves: 30; color: blue"> 
```

**Comment by msimpson** [comment]
@ngokevin 
I like that idea. It would decouple data retrieval (i.e. XHR) and modeling from the actual template even further.

**Comment by ngokevin** [comment]
Added!
