### ISSUE TITLE
no type insertion should work

### ISSUE THREAD

**Issue by andreasplesch** [ngokevin/aframe-template-component#7]
A template with no type specified such as:

<a-entity template='src:helloworld_aframe.html'></a-entity>

should work by jsut inserting the unprocessed document fragment. Here is an example scene:

http://andreasplesch.github.io/aframe-pages/test/htmlinclude/no_type_template.html

PR #6 adds a few lines to fix this case. Here is the same scene with the patched component:

http://andreasplesch.github.io/aframe-pages/test/htmlinclude/by_template.html

**Comment by ngokevin** [comment]
Dupe https://github.com/ngokevin/aframe-template-component/issues/2 but fixed!
