### ISSUE TITLE
fragile lazy loading ?

### ISSUE THREAD

**Issue by andreasplesch** [ngokevin/aframe-template-component#8]
The on demand loading of the template engines reduces file size but introduces a dependency on the hosting of the library. cloudflare should be around but still a potential headache.

One way to make this more robust/future-proof is to allow for a fall back source for a library:

https://cdn.jsdelivr.net/handlebarsjs/4.0.5/handlebars.min.js (recommend by handlebar)
https://cdn.jsdelivr.net/mustache.js/2.2.1/mustache.min.js
https://cdn.jsdelivr.net/nunjucks/2.3.0/nunjucks.min.js

I could not find jade 1.11, jsdelivr only has
https://cdn.jsdelivr.net/jade/1.3.1/jade.min.js

**Comment by ngokevin** [comment]
When you use lazy-loading, there will be a console.log that recommends that you download/`wget` and host the bundle. Is that enough?

**Comment by andreasplesch** [comment]
Of course. Good solution.
